version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}


services:
  crawler:
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile
    depends_on:
      - postgres
    network_mode: "host"
    ports:
      - "6881:6881"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: "localhost"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/production/Dockerfile
    depends_on:
      - postgres
      - crawler
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env

  postgres:
    build:
      context: .
      dockerfile: docker/persistence/Dockerfile
    image: stilio_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env
